// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['webApiKey'].toString(),
    appId: dotenv.env['webAppId'].toString(),
    messagingSenderId: dotenv.env['messagingSenderId'].toString(),
    projectId: dotenv.env['projectId'].toString(),
    authDomain: dotenv.env['authDomain'].toString(),
    storageBucket: dotenv.env['storageBucket'].toString(),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['androidApiKey'].toString(),
    appId: dotenv.env['androidAppId'].toString(),
    messagingSenderId: dotenv.env['messagingSenderId'].toString(),
    projectId: dotenv.env['projectId'].toString(),
    storageBucket: dotenv.env['storageBucket'].toString(),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['iosApiKey'].toString(),
    appId: dotenv.env['iosAppId'].toString(),
    messagingSenderId: dotenv.env['messagingSenderId'].toString(),
    projectId: dotenv.env['projectId'].toString(),
    storageBucket: dotenv.env['storageBucket'].toString(),
    iosBundleId: dotenv.env['iosBundleId'].toString(),
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['iosAppId'].toString(),
    appId: dotenv.env['macosAppId'].toString(),
    messagingSenderId: dotenv.env['messagingSenderId'].toString(),
    projectId: dotenv.env['projectId'].toString(),
    storageBucket: dotenv.env['storageBucket'].toString(),
    iosBundleId: dotenv.env['macosBundleId'].toString(),
  );
}
